import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  viewBody: {
    flex: 1,
    paddingHorizontal: 32,
  },
  viewButtonBody: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  viewIconNext: {
    backgroundColor: colors.borderBackground,
    height: 48,
    width: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageIconNext: { height: 24, width: 16, tintColor: colors.white },
  textTitle: {
    fontSize: 18,
    color: colors.black,
    marginBottom: 8,
  },
  viewButtonDropDown: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  buttonDropDown: {
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    borderColor: colors.borderBackground,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 45,
    borderRadius: 4,
  },
  textDropDown: { fontSize: 16, color: colors.black },
  viewCheckBoxItem: {
    flexDirection: 'row',
  },
  viewCheckBoxFormItem: {
    backgroundColor: colors.white,
    borderColor: colors.borderBackground,
    borderRadius: 50,
    borderWidth: 2,
    height: 24,
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  viewImageSelectItem: {
    height: 12,
    width: 12,
  },
  imageSelectItem: {
    height: 12,
    width: 12,
  },
  viewTextSelect: {
    backgroundColor: colors.backgroundStatusBar,
  },
  textSelect: {
    fontSize: 18,
    color: colors.black,
    paddingHorizontal: 8,
  },
  textComponents: { fontSize: 24, color: colors.black, fontWeight: 'bold' },
  viewItemHeaderComponents: {
    backgroundColor: colors.lightBlue,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 0.2,
    shadowColor: colors.lightBlue,
  },
  textItemHeaderComponents: {
    fontSize: 18,
    color: colors.primary
  },
  viewItemBodyComponents: {
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
  },
  textItemBodyComponents: { fontSize: 17, color: colors.black, },
  viewButtonFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
    marginVertical: 16,
  },
  buttonDelete: {
    backgroundColor: colors.colorTextInput,
    height: 48,
    width: 48,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  imageDeleteButton: { height: 32, width: 32 },
  viewTextComponents: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewPrice: {
    backgroundColor: colors.white,
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  viewTotalPrice: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  textPrice: {
    fontSize: 18,
    color: colors.black,
    width: '20%',
    textAlign: 'right',
  },
  headerTableText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 18,
  },
});
